sonar.projectKey=ImplementSprint_template-repo-be-single
sonar.organization=implementsprint

sonar.sources=src
sonar.tests=src,test
sonar.test.inclusions=**/*.spec.ts,test/**/*.ts
sonar.exclusions=dist/**,node_modules/**
sonar.coverage.exclusions=src/main.ts,src/**/*.module.ts

sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true
